Adds an ADR for graphql
sul-dlss-labs/infrastructure-adrs pull request #41
Opened 2023-08-30 15:15 UTC by justinlittman

2023-08-30 15:34 UTC, aaron-collier approved these changes

2023-08-30 16:18 UTC, edsu requested changes

2023-08-30 16:18 UTC, edsu commented on 0018-graphql.md
> +* Graphql has the possibility to re-used to address other use cases.
to *be* re-used

2023-08-30 16:18 UTC, edsu commented on 0018-graphql.md
> +* Con: Requires adding an additional component to DSA.
If I remember right it also introduces a new variant type of Cocina models that do not require validation?

2023-08-30 16:18 UTC, edsu commented on 0018-graphql.md
> +* Con: Infra team is not familiar with Graphql.
Con: ruby-graphql is split into a free/pro versions. As our usage increases we may find ourselves needing the pro features, and will need to pay for it.

2023-08-30 16:18 UTC, edsu commented on 0018-graphql.md
> +* Con: Does not address other possible use cases.
Since this ADR does not discuss any of these additional use cases it's not really a Con is it?

2023-08-30 16:18 UTC, edsu commented on 0018-graphql.md
> +* Con: Because of the way that Argo is deployed (multiple processes on multiple servers), the recommended approach is to use memcache. However, a memcache system is significant infrastructure and is
Have ops said they would not memcache? I believe that Redis could be used as well?

2023-08-30 17:19 UTC, justinlittman commented on 0018-graphql.md
> +* Graphql has the possibility to re-used to address other use cases.
Fixed.

2023-08-30 17:20 UTC, justinlittman commented on 0018-graphql.md
> +* Con: Requires adding an additional component to DSA.
You remember right. I added a mention of this in earlier section.

2023-08-30 17:21 UTC, justinlittman commented on 0018-graphql.md
> +* Con: Does not address other possible use cases.
They are listed on L65.

2023-08-30 17:25 UTC, justinlittman commented on 0018-graphql.md
> +* Con: Because of the way that Argo is deployed (multiple processes on multiple servers), the recommended approach is to use memcache. However, a memcache system is significant infrastructure and is
Ops response was that they don't currently support it in puppet and don't have any expertise with managing it, so using it would not be preferable unless critical.

Redis can be used, but the guidance is to not use the same redis instance as is being used for activejob. Also, since deploy of redis or memcache would have to be on a separate server (and thus incur a network penalty) it isn't clear how much of a performance boost would be provided.

2023-08-30 17:34 UTC, edsu commented on 0018-graphql.md
> +* Con: Does not address other possible use cases.
Oh right, sorry I missed that.

2023-08-30 17:43 UTC, edsu commented on 0018-graphql.md
> +* Con: Because of the way that Argo is deployed (multiple processes on multiple servers), the recommended approach is to use memcache. However, a memcache system is significant infrastructure and is
Just pointing out that Redis does have multiple databases, you usually connect to db 0, but we could (in theory) use another db namespace for the cache.

2023-08-30 18:31 UTC, justinlittman commented on 0018-graphql.md
> +* Con: Because of the way that Argo is deployed (multiple processes on multiple servers), the recommended approach is to use memcache. However, a memcache system is significant infrastructure and is
Oh, I hadn't thought of that. But still not sure it will provide a performance boost in the case of Argo, especially given that the requests are likely to be concurrent.

2023-08-30 18:33 UTC, justinlittman commented on 0018-graphql.md
> +* Con: Infra team is not familiar with Graphql.
Added.

2023-09-01 12:30 UTC, edsu approved these changes

2023-09-01 13:49 UTC, lwrubel approved these changes

2023-09-01 13:51 UTC, lwrubel commented on 0018-graphql.md
> +* The opportunity to reuse new machinery / infrastructure of address other use cases.
typo? `infrastructure of address other use cases`

2023-09-01 17:51 UTC, justinlittman commented on 0018-graphql.md
> +* The opportunity to reuse new machinery / infrastructure of address other use cases.
Thanks. Fixed.

2023-09-01 17:51 UTC, merged